import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

const GATEWAY_URL = "https://ai.gateway.lovable.dev/v1/chat/completions";
const MODEL_PRO = "google/gemini-3.1-pro-preview";
const MODEL_FAST = "google/gemini-3-flash-preview";

async function callGateway(body: any) {
  const apiKey = process.env.LOVABLE_API_KEY;
  if (!apiKey) throw new Error("AI gateway not configured.");
  const res = await fetch(GATEWAY_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
    body: JSON.stringify(body),
  });
  if (res.status === 429) throw new Error("Rate limited — try again in a moment.");
  if (res.status === 402) throw new Error("AI credits exhausted on the platform.");
  if (!res.ok) {
    const t = await res.text().catch(() => "");
    console.error("[AI gateway]", res.status, t);
    throw new Error("AI request failed. Please try again.");
  }
  return res.json();
}

async function getPlanAndCredits(supabase: any, userId: string) {
  const { data } = await supabase.from("profiles").select("plan, monthly_credit_override").eq("id", userId).maybeSingle();
  const plan = (data?.plan as string) || "free";
  const limits: Record<string, { day: number; month: number }> = {
    free: { day: 10, month: 100 },
    pro: { day: 100, month: 1000 },
    max: { day: 500, month: 10000 },
  };
  const l = limits[plan] || limits.free;
  const today = new Date().toISOString().slice(0, 10);
  const month = today.slice(0, 7);
  const { count: dayUsed } = await supabase.from("ai_usage").select("id", { count: "exact", head: true }).eq("user_id", userId).eq("day", today);
  const { count: monthUsed } = await supabase.from("ai_usage").select("id", { count: "exact", head: true }).eq("user_id", userId).eq("month", month);
  const monthLimit = data?.monthly_credit_override ?? l.month;
  if ((dayUsed ?? 0) >= l.day) throw new Error(`Daily AI limit reached (${l.day}/day on the ${plan} plan).`);
  if ((monthUsed ?? 0) >= monthLimit) throw new Error(`Monthly AI limit reached (${monthLimit}/month on the ${plan} plan).`);
  return { plan };
}

async function recordUsage(userId: string, model: string, inTok = 0, outTok = 0, kind = "chat", plan = "free") {
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  await supabaseAdmin.from("ai_usage").insert({ user_id: userId, model, tokens_in: inTok, tokens_out: outTok, kind, plan });
}

// ---- Research Agent (Max plan only) ----
// Multi-step reasoning: outline → expand each section → citations placeholder
export const aiResearchAgent = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input) => z.object({
    topic: z.string().min(3).max(500),
    depth: z.enum(["brief", "standard", "deep"]).default("standard"),
  }).parse(input))
  .handler(async ({ data, context }) => {
    const { userId, supabase } = context as any;
    const { plan } = await getPlanAndCredits(supabase, userId);
    if (plan !== "max") {
      throw new Error("AI Research Agent is a MAX plan feature. Upgrade to unlock multi-step research.");
    }

    // Step 1: outline
    const outlineRes = await callGateway({
      model: MODEL_FAST,
      messages: [
        { role: "system", content: "You are a research planner. Output ONLY JSON: {\"outline\":[{\"heading\":string,\"questions\":[string]}]}. Produce 4-6 sections that fully cover the topic." },
        { role: "user", content: data.topic },
      ],
      response_format: { type: "json_object" },
    });
    let outline: any = {};
    try { outline = JSON.parse(outlineRes.choices?.[0]?.message?.content ?? "{}"); } catch {}
    const sections = Array.isArray(outline.outline) ? outline.outline.slice(0, 6) : [];

    // Step 2: expand each section with pro model
    const expanded: any[] = [];
    const wordTarget = data.depth === "deep" ? 250 : data.depth === "standard" ? 150 : 80;
    for (const s of sections) {
      const r = await callGateway({
        model: MODEL_PRO,
        messages: [
          { role: "system", content: `You are writing part of a research brief. Write ~${wordTarget} words of clear, well-structured HTML for this section only. Use <h2> for the heading, then <p>, <ul>, <blockquote> as needed. No <html> or <body>.` },
          { role: "user", content: `Topic: ${data.topic}\n\nSection: ${s.heading}\nGuiding questions:\n${(s.questions ?? []).map((q: string) => "- " + q).join("\n")}` },
        ],
      });
      expanded.push({ heading: s.heading, html: r.choices?.[0]?.message?.content ?? "" });
    }

    await recordUsage(userId, MODEL_PRO, 0, 0, "research", plan);

    const html =
      `<h1>${escapeHtml(data.topic)}</h1>` +
      `<p><em>Research brief generated by Focusly AI (Max)</em></p>` +
      expanded.map((e) => e.html).join("\n") +
      `<h2>Suggested next steps</h2><ul><li>Verify claims against primary sources.</li><li>Add specific citations for each section.</li><li>Refine the brief with your own perspective.</li></ul>`;

    return { html, sections: expanded.length, plan };
  });

// ---- Rubric grader (Max plan only) ----
export const aiGradeDoc = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input) => z.object({
    doc_text: z.string().min(20).max(30000),
    rubric: z.string().min(10).max(5000),
  }).parse(input))
  .handler(async ({ data, context }) => {
    const { userId, supabase } = context as any;
    const { plan } = await getPlanAndCredits(supabase, userId);
    if (plan !== "max") {
      throw new Error("AI Grader is a MAX plan feature. Upgrade to unlock rubric grading.");
    }
    const sys = `You are a strict but fair teacher. Grade the student's document against the provided rubric.
Return ONLY JSON:
{
  "overall_score": number (0-100),
  "letter": string,
  "criteria": [{"name":string,"score":number,"max":number,"feedback":string}],
  "strengths": [string],
  "improvements": [string],
  "revision_notes": string
}`;
    const r = await callGateway({
      model: MODEL_PRO,
      messages: [
        { role: "system", content: sys },
        { role: "user", content: `RUBRIC:\n${data.rubric}\n\n---\n\nDOCUMENT:\n${data.doc_text}` },
      ],
      response_format: { type: "json_object" },
    });
    const raw = r.choices?.[0]?.message?.content ?? "{}";
    let parsed: any = {};
    try { parsed = JSON.parse(raw); } catch {}
    await recordUsage(userId, MODEL_PRO, 0, 0, "grade", plan);
    return {
      overall_score: typeof parsed.overall_score === "number" ? Math.round(parsed.overall_score) : 0,
      letter: typeof parsed.letter === "string" ? parsed.letter : "",
      criteria: Array.isArray(parsed.criteria) ? parsed.criteria.slice(0, 12) : [],
      strengths: Array.isArray(parsed.strengths) ? parsed.strengths.slice(0, 8) : [],
      improvements: Array.isArray(parsed.improvements) ? parsed.improvements.slice(0, 8) : [],
      revision_notes: typeof parsed.revision_notes === "string" ? parsed.revision_notes : "",
      plan,
    };
  });

// ---- Doc-level rewrite / expand (available to all plans, MAX gets pro model) ----
export const aiRewrite = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input) => z.object({
    text: z.string().min(1).max(8000),
    action: z.enum(["improve", "shorten", "expand", "formal", "casual", "fix_grammar"]),
  }).parse(input))
  .handler(async ({ data, context }) => {
    const { userId, supabase } = context as any;
    const { plan } = await getPlanAndCredits(supabase, userId);
    const model = plan === "max" ? MODEL_PRO : MODEL_FAST;
    const instructions: Record<string, string> = {
      improve: "Rewrite the text so it flows better and reads more clearly. Preserve meaning.",
      shorten: "Rewrite the text more concisely. Preserve meaning.",
      expand: "Expand the text with more supporting detail and examples.",
      formal: "Rewrite in a more formal, academic tone.",
      casual: "Rewrite in a friendlier, more conversational tone.",
      fix_grammar: "Fix grammar, spelling, and punctuation only. Do not change meaning or style.",
    };
    const r = await callGateway({
      model,
      messages: [
        { role: "system", content: `You rewrite prose. ${instructions[data.action]} Return only the rewritten text — no preamble, no quotes.` },
        { role: "user", content: data.text },
      ],
    });
    const out = r.choices?.[0]?.message?.content?.trim() ?? "";
    await recordUsage(userId, model, 0, 0, `rewrite_${data.action}`, plan);
    return { text: out, plan };
  });

function escapeHtml(s: string) {
  return s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] as string));
}
