/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as EngagementRouteImport } from './routes/engagement'
import { Route as DocsProbeRouteImport } from './routes/docs-probe'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpdatesSlugRouteImport } from './routes/updates.$slug'
import { Route as AuthenticatedUsageRouteImport } from './routes/_authenticated/usage'
import { Route as AuthenticatedSocialRouteImport } from './routes/_authenticated/social'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedDocsRouteImport } from './routes/_authenticated/docs'
import { Route as AuthenticatedCardsRouteImport } from './routes/_authenticated/cards'
import { Route as AuthenticatedCalenderRouteImport } from './routes/_authenticated/calender'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDocsIndexRouteImport } from './routes/_authenticated/docs.index'
import { Route as DocsShareTokenRouteImport } from './routes/docs.share.$token'
import { Route as ApiPublicExtensionVersionRouteImport } from './routes/api/public/extension-version'
import { Route as AuthenticatedDocsIdRouteImport } from './routes/_authenticated/docs.$id'
import { Route as AuthenticatedAssignmentsIdRouteImport } from './routes/_authenticated/assignments.$id'

const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementRoute = EngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsProbeRoute = DocsProbeRouteImport.update({
  id: '/docs-probe',
  path: '/docs-probe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesSlugRoute = UpdatesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => UpdatesRoute,
} as any)
const AuthenticatedUsageRoute = AuthenticatedUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocialRoute = AuthenticatedSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocsRoute = AuthenticatedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCardsRoute = AuthenticatedCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalenderRoute = AuthenticatedCalenderRouteImport.update({
  id: '/calender',
  path: '/calender',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocsIndexRoute = AuthenticatedDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDocsRoute,
} as any)
const DocsShareTokenRoute = DocsShareTokenRouteImport.update({
  id: '/docs/share/$token',
  path: '/docs/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtensionVersionRoute =
  ApiPublicExtensionVersionRouteImport.update({
    id: '/api/public/extension-version',
    path: '/api/public/extension-version',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDocsIdRoute = AuthenticatedDocsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDocsRoute,
} as any)
const AuthenticatedAssignmentsIdRoute =
  AuthenticatedAssignmentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAssignmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs-probe': typeof DocsProbeRoute
  '/engagement': typeof EngagementRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/redeem': typeof RedeemRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/updates': typeof UpdatesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/assignments': typeof AuthenticatedAssignmentsRouteWithChildren
  '/calender': typeof AuthenticatedCalenderRoute
  '/cards': typeof AuthenticatedCardsRoute
  '/docs': typeof AuthenticatedDocsRouteWithChildren
  '/notes': typeof AuthenticatedNotesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/social': typeof AuthenticatedSocialRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/assignments/$id': typeof AuthenticatedAssignmentsIdRoute
  '/docs/$id': typeof AuthenticatedDocsIdRoute
  '/api/public/extension-version': typeof ApiPublicExtensionVersionRoute
  '/docs/share/$token': typeof DocsShareTokenRoute
  '/docs/': typeof AuthenticatedDocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs-probe': typeof DocsProbeRoute
  '/engagement': typeof EngagementRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/redeem': typeof RedeemRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/updates': typeof UpdatesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/assignments': typeof AuthenticatedAssignmentsRouteWithChildren
  '/calender': typeof AuthenticatedCalenderRoute
  '/cards': typeof AuthenticatedCardsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/social': typeof AuthenticatedSocialRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/assignments/$id': typeof AuthenticatedAssignmentsIdRoute
  '/docs/$id': typeof AuthenticatedDocsIdRoute
  '/api/public/extension-version': typeof ApiPublicExtensionVersionRoute
  '/docs/share/$token': typeof DocsShareTokenRoute
  '/docs': typeof AuthenticatedDocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/docs-probe': typeof DocsProbeRoute
  '/engagement': typeof EngagementRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/redeem': typeof RedeemRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/updates': typeof UpdatesRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRouteWithChildren
  '/_authenticated/calender': typeof AuthenticatedCalenderRoute
  '/_authenticated/cards': typeof AuthenticatedCardsRoute
  '/_authenticated/docs': typeof AuthenticatedDocsRouteWithChildren
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/social': typeof AuthenticatedSocialRoute
  '/_authenticated/usage': typeof AuthenticatedUsageRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/_authenticated/assignments/$id': typeof AuthenticatedAssignmentsIdRoute
  '/_authenticated/docs/$id': typeof AuthenticatedDocsIdRoute
  '/api/public/extension-version': typeof ApiPublicExtensionVersionRoute
  '/docs/share/$token': typeof DocsShareTokenRoute
  '/_authenticated/docs/': typeof AuthenticatedDocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs-probe'
    | '/engagement'
    | '/landing'
    | '/login'
    | '/plans'
    | '/redeem'
    | '/signup'
    | '/support'
    | '/updates'
    | '/admin'
    | '/app'
    | '/assignments'
    | '/calender'
    | '/cards'
    | '/docs'
    | '/notes'
    | '/settings'
    | '/social'
    | '/usage'
    | '/updates/$slug'
    | '/assignments/$id'
    | '/docs/$id'
    | '/api/public/extension-version'
    | '/docs/share/$token'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs-probe'
    | '/engagement'
    | '/landing'
    | '/login'
    | '/plans'
    | '/redeem'
    | '/signup'
    | '/support'
    | '/updates'
    | '/admin'
    | '/app'
    | '/assignments'
    | '/calender'
    | '/cards'
    | '/notes'
    | '/settings'
    | '/social'
    | '/usage'
    | '/updates/$slug'
    | '/assignments/$id'
    | '/docs/$id'
    | '/api/public/extension-version'
    | '/docs/share/$token'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/docs-probe'
    | '/engagement'
    | '/landing'
    | '/login'
    | '/plans'
    | '/redeem'
    | '/signup'
    | '/support'
    | '/updates'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/assignments'
    | '/_authenticated/calender'
    | '/_authenticated/cards'
    | '/_authenticated/docs'
    | '/_authenticated/notes'
    | '/_authenticated/settings'
    | '/_authenticated/social'
    | '/_authenticated/usage'
    | '/updates/$slug'
    | '/_authenticated/assignments/$id'
    | '/_authenticated/docs/$id'
    | '/api/public/extension-version'
    | '/docs/share/$token'
    | '/_authenticated/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DocsProbeRoute: typeof DocsProbeRoute
  EngagementRoute: typeof EngagementRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRoute
  RedeemRoute: typeof RedeemRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  UpdatesRoute: typeof UpdatesRouteWithChildren
  ApiPublicExtensionVersionRoute: typeof ApiPublicExtensionVersionRoute
  DocsShareTokenRoute: typeof DocsShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement': {
      id: '/engagement'
      path: '/engagement'
      fullPath: '/engagement'
      preLoaderRoute: typeof EngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs-probe': {
      id: '/docs-probe'
      path: '/docs-probe'
      fullPath: '/docs-probe'
      preLoaderRoute: typeof DocsProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/$slug': {
      id: '/updates/$slug'
      path: '/$slug'
      fullPath: '/updates/$slug'
      preLoaderRoute: typeof UpdatesSlugRouteImport
      parentRoute: typeof UpdatesRoute
    }
    '/_authenticated/usage': {
      id: '/_authenticated/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthenticatedUsageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social': {
      id: '/_authenticated/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedSocialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/docs': {
      id: '/_authenticated/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthenticatedDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cards': {
      id: '/_authenticated/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AuthenticatedCardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calender': {
      id: '/_authenticated/calender'
      path: '/calender'
      fullPath: '/calender'
      preLoaderRoute: typeof AuthenticatedCalenderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/docs/': {
      id: '/_authenticated/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof AuthenticatedDocsIndexRouteImport
      parentRoute: typeof AuthenticatedDocsRoute
    }
    '/docs/share/$token': {
      id: '/docs/share/$token'
      path: '/docs/share/$token'
      fullPath: '/docs/share/$token'
      preLoaderRoute: typeof DocsShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension-version': {
      id: '/api/public/extension-version'
      path: '/api/public/extension-version'
      fullPath: '/api/public/extension-version'
      preLoaderRoute: typeof ApiPublicExtensionVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/docs/$id': {
      id: '/_authenticated/docs/$id'
      path: '/$id'
      fullPath: '/docs/$id'
      preLoaderRoute: typeof AuthenticatedDocsIdRouteImport
      parentRoute: typeof AuthenticatedDocsRoute
    }
    '/_authenticated/assignments/$id': {
      id: '/_authenticated/assignments/$id'
      path: '/$id'
      fullPath: '/assignments/$id'
      preLoaderRoute: typeof AuthenticatedAssignmentsIdRouteImport
      parentRoute: typeof AuthenticatedAssignmentsRoute
    }
  }
}

interface AuthenticatedAssignmentsRouteChildren {
  AuthenticatedAssignmentsIdRoute: typeof AuthenticatedAssignmentsIdRoute
}

const AuthenticatedAssignmentsRouteChildren: AuthenticatedAssignmentsRouteChildren =
  {
    AuthenticatedAssignmentsIdRoute: AuthenticatedAssignmentsIdRoute,
  }

const AuthenticatedAssignmentsRouteWithChildren =
  AuthenticatedAssignmentsRoute._addFileChildren(
    AuthenticatedAssignmentsRouteChildren,
  )

interface AuthenticatedDocsRouteChildren {
  AuthenticatedDocsIdRoute: typeof AuthenticatedDocsIdRoute
  AuthenticatedDocsIndexRoute: typeof AuthenticatedDocsIndexRoute
}

const AuthenticatedDocsRouteChildren: AuthenticatedDocsRouteChildren = {
  AuthenticatedDocsIdRoute: AuthenticatedDocsIdRoute,
  AuthenticatedDocsIndexRoute: AuthenticatedDocsIndexRoute,
}

const AuthenticatedDocsRouteWithChildren =
  AuthenticatedDocsRoute._addFileChildren(AuthenticatedDocsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRouteWithChildren
  AuthenticatedCalenderRoute: typeof AuthenticatedCalenderRoute
  AuthenticatedCardsRoute: typeof AuthenticatedCardsRoute
  AuthenticatedDocsRoute: typeof AuthenticatedDocsRouteWithChildren
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSocialRoute: typeof AuthenticatedSocialRoute
  AuthenticatedUsageRoute: typeof AuthenticatedUsageRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRouteWithChildren,
  AuthenticatedCalenderRoute: AuthenticatedCalenderRoute,
  AuthenticatedCardsRoute: AuthenticatedCardsRoute,
  AuthenticatedDocsRoute: AuthenticatedDocsRouteWithChildren,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSocialRoute: AuthenticatedSocialRoute,
  AuthenticatedUsageRoute: AuthenticatedUsageRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface UpdatesRouteChildren {
  UpdatesSlugRoute: typeof UpdatesSlugRoute
}

const UpdatesRouteChildren: UpdatesRouteChildren = {
  UpdatesSlugRoute: UpdatesSlugRoute,
}

const UpdatesRouteWithChildren =
  UpdatesRoute._addFileChildren(UpdatesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DocsProbeRoute: DocsProbeRoute,
  EngagementRoute: EngagementRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  RedeemRoute: RedeemRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  UpdatesRoute: UpdatesRouteWithChildren,
  ApiPublicExtensionVersionRoute: ApiPublicExtensionVersionRoute,
  DocsShareTokenRoute: DocsShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
